import assert from "node:assert/strict";
import {createRequire} from "node:module";
import {mkdir} from "node:fs/promises";
import {fileURLToPath} from "node:url";
import {startUiServer} from "./ui_server_process.mjs";
const {chromium}=createRequire(import.meta.url)(process.argv[3]||"playwright");
let server,browser,checks=0;
try{
    server=await startUiServer(process.argv[2],[fileURLToPath(new URL("./animate_video_ui_server.py",import.meta.url))]);
    const url=server.url;
    browser=await chromium.launch({headless:true,executablePath:process.argv[4]||undefined});
    const page=await browser.newPage({viewport:{width:1240,height:800}}),errors=[];page.on("pageerror",error=>errors.push(error.message));
    await page.goto(url);await page.waitForFunction(()=>desk.zvAnimate.getPlan()?.segments.length===3);
    const pane=page.locator(".zv-animate"),plan=()=>page.evaluate(()=>desk.zvAnimate.getPlan());
    const original=await page.evaluate(()=>sourceNode.widgets[0].value);
    assert.equal(await pane.locator("select").count(),1);assert.equal(await pane.locator("button,input,textarea,.playhead,.edge").count(),1);checks+=2;
    assert.equal(await pane.locator(".pair").count(),3);assert.equal(await pane.locator(".clip").count(),3);checks+=2;
    assert.equal((await plan()).fps,30);assert.equal((await plan()).fps_origin,"workflow");assert.match(await pane.locator(".summary").textContent(),/沿用原流 30 fps/);checks+=3;
    assert.deepEqual((await plan()).segments.map(row=>row.frame_count),[200,200,210]);assert.equal((await plan()).target_frame_count,610);checks+=2;
    assert((await plan()).validation.ready);assert((await plan()).segments.every(row=>row.guide_frame_count===0));checks+=2;
    const mode=pane.getByLabel("段间衔接",{exact:true});await mode.selectOption("continuation_21");await page.waitForFunction(()=>desk.zvAnimate.getPlan()?.settings.seam_mode==='continuation_21');
    assert.deepEqual((await plan()).segments.map(row=>row.guide_frame_count),[0,21,21]);assert((await plan()).segments.every(row=>row.contribution_start_frame===0));checks+=2;
    assert.equal(await page.evaluate(()=>sourceNode.widgets[0].value),original);checks++;
    const maskToggle=pane.getByLabel("遮罩管道",{exact:true});
    assert.equal(await pane.locator('input[type=checkbox]').count(),1);checks++;
    await maskToggle.check();await page.waitForFunction(()=>desk.zvAnimate.getPlan()?.settings.mask_enabled);
    assert.equal(await pane.locator('.mask-fields').count(),3);assert(!(await plan()).validation.ready);checks+=2;
    for(let i=1;i<=3;i++){
        const prompt=pane.getByLabel(`第 ${i} 段遮罩目标词`,{exact:true}),frame=pane.getByLabel(`第 ${i} 段参考帧`,{exact:true});
        await prompt.fill(`目标 ${i}`);await prompt.press('Enter');
        await page.waitForFunction(i=>desk.zvAnimate.getPlan()?.settings.mask_tasks[`clip${i}`]?.prompt===`目标 ${i}`,i);
        await frame.fill(String((i-1)*200+1));await frame.press('Enter');
        await page.waitForFunction(i=>desk.zvAnimate.getPlan()?.settings.mask_tasks[`clip${i}`]?.source_frame===(i-1)*200,i);
    }
    assert((await plan()).validation.ready);assert.deepEqual((await plan()).segments.map(row=>row.mask_task.local_index),[0,0,0]);checks+=2;
    const savedMask=await page.evaluate(()=>desk.widgets[0].value);
    await page.evaluate(()=>desk.zvAnimate.restore());await page.waitForFunction(()=>desk.zvAnimate.getPlan()?.validation.ready);
    assert.equal(await pane.getByLabel('第 2 段参考帧',{exact:true}).inputValue(),'201');assert.equal(await page.evaluate(()=>desk.widgets[0].value),savedMask);checks+=2;
    if(process.argv[5]){await mkdir(process.argv[5],{recursive:true});await page.screenshot({path:`${process.argv[5]}/animate-global-mask.png`,fullPage:true});}
    await pane.getByLabel('第 2 段参考帧',{exact:true}).fill('415');await pane.getByLabel('第 2 段参考帧',{exact:true}).press('Enter');
    await page.waitForFunction(()=>desk.zvAnimate.getPlan()?.validation.errors.some(row=>row.code==='mask_frame_range'));
    assert.match(await pane.locator('.status').textContent(),/第 2 段.*201–400/);checks++;
    await maskToggle.uncheck();await page.waitForFunction(()=>desk.zvAnimate.getPlan()?.settings.mask_enabled===false);
    assert((await plan()).validation.ready);assert.equal(await pane.locator('.mask-fields').count(),0);checks+=2;
    const stored=(await plan()).settings.mask_tasks;
    await mode.selectOption('hard_cut');await page.waitForFunction(()=>desk.zvAnimate.getPlan()?.settings.seam_mode==='hard_cut');
    assert.deepEqual((await plan()).settings.mask_tasks,stored);checks++;
    await mode.selectOption('continuation_21');await page.waitForFunction(()=>desk.zvAnimate.getPlan()?.settings.seam_mode==='continuation_21');
    await page.evaluate(()=>{const p=JSON.parse(sourceNode.widgets[0].value);p.picture_track=p.picture_track.slice(0,1);sourceNode.widgets[0].value=JSON.stringify(p);});
    await page.waitForFunction(()=>desk.zvAnimate.getPlan()?.pictures.length===1);assert(!(await plan()).validation.ready);assert.equal(await pane.locator(".pair.missing").count(),2);checks+=2;
    assert.match(await pane.locator(".status").textContent(),/一一对应/);checks++;
    await page.evaluate(value=>{sourceNode.widgets[0].value=value;},original);await page.waitForFunction(()=>desk.zvAnimate.getPlan()?.validation.ready);
    await page.evaluate(()=>{fpsNode.widgets[0].value=60;});await page.waitForFunction(()=>desk.zvAnimate.getPlan()?.fps===60);
    assert.equal((await plan()).target_frame_count,1220);assert.equal((await plan()).media_project.video_track[1].source_in_seconds,200/30);checks+=2;
    await page.evaluate(()=>{fpsNode.widgets[0].value=29;});await page.waitForFunction(()=>desk.zvAnimate.getPlan()?.fps===29);
    assert(!(await plan()).validation.ready);assert.match(await pane.locator(".status").textContent(),/切点不在同一网格/);checks+=2;
    await page.evaluate(()=>{fpsNode.widgets[0].value=30;});await page.waitForFunction(()=>desk.zvAnimate.getPlan()?.fps===30);
    await page.evaluate(()=>{const p=JSON.parse(sourceNode.widgets[0].value);p.video_track[0].source_out_seconds=199/30;p.audio_track[0].source_out_seconds=199/30;sourceNode.widgets[0].value=JSON.stringify(p);});
    await page.waitForFunction(()=>desk.zvAnimate.getPlan()?.segments[0]?.frame_count===199);
    assert.equal((await plan()).segments[0].source_end_seconds,199/30);assert.equal((await plan()).target_frame_count,609);checks+=2;
    await page.evaluate(()=>{const p=JSON.parse(sourceNode.widgets[0].value);p.video_track[0].timeline_in_seconds=25;p.audio_track[0].timeline_in_seconds=25;sourceNode.widgets[0].value=JSON.stringify(p);});
    await page.waitForFunction(()=>desk.zvAnimate.getPlan()?.segments[0]?.clip_id==='clip2');assert.equal((await plan()).segments.at(-1).clip_id,"clip1");checks++;
    const saved=await page.evaluate(()=>desk.widgets[0].value);await page.evaluate(()=>desk.zvAnimate.restore());await page.waitForFunction(()=>desk.zvAnimate.getPlan()?.validation.ready);assert.equal(await page.evaluate(()=>desk.widgets[0].value),saved);checks++;
    await page.evaluate(()=>{window.actualGetInputNode=desk.getInputNode;desk.getInputNode=index=>index===1?fpsNode:null;});await page.waitForFunction(()=>desk.zvAnimate.getPlan()===null);assert.match(await pane.locator(".status").textContent(),/连接/);checks++;
    await page.evaluate(()=>{desk.getInputNode=window.actualGetInputNode;desk.onConnectionsChange();});await page.waitForFunction(()=>desk.zvAnimate.getPlan()?.segments.length===3);checks++;
    assert.deepEqual(errors,[]);checks++;
    const directory=process.argv[5];if(directory){await mkdir(directory,{recursive:true});await page.screenshot({path:`${directory}/animate-native-seams.png`,fullPage:true});}
    await page.evaluate(()=>desk.onRemoved());assert.equal(await pane.count(),0);checks++;
    console.log(JSON.stringify({checks,passed:true,url}));
}finally{try{await browser?.close();}finally{await server?.stop();}}
