import assert from "node:assert/strict";
import {createRequire} from "node:module";
import {spawn} from "node:child_process";
import {mkdir} from "node:fs/promises";
const {chromium}=createRequire(import.meta.url)(process.argv[3]||"playwright");
const server=spawn(process.argv[2],[new URL("./long_video_ui_server.py",import.meta.url).pathname.replace(/^\/([A-Z]:)/i,"$1")],{windowsHide:true,stdio:["ignore","pipe","pipe"]});
const url=await new Promise((resolve,reject)=>{server.stdout.once("data",data=>resolve(String(data).trim()));server.stderr.on("data",data=>reject(new Error(String(data))));server.on("exit",code=>reject(new Error(`harness exit ${code}`)));});
let browser;
try{
    browser=await chromium.launch({headless:true,executablePath:process.argv[4]||undefined});
    const page=await browser.newPage({viewport:{width:1240,height:1000}}),errors=[];
    page.on("pageerror",error=>errors.push(error.message));
    await page.goto(url);await page.waitForFunction(()=>desk.zvLong.getPlan()?.segments.length===2);
    const pane=page.locator("#desk");
    assert.equal(await pane.locator(".lane").count(),4);
    assert.equal(await pane.getByLabel("段数（仅按段数生成）",{exact:true}).isDisabled(),true);
    assert.match(await pane.getByLabel("段数（仅按段数生成）",{exact:true}).getAttribute("title"),/自动计算/);
    assert.match(await pane.locator(".hint").textContent(),/8–15 秒.*5\+17k.*裁回.*1 或 5\+17k/);
    await pane.locator(".card.segment").first().click();
    const ruler= pane.locator(".ruler");
    const rulerPoint=await ruler.evaluate((element,frame)=>{const rect=element.getBoundingClientRect(),ratio=rect.width/element.offsetWidth;return {x:rect.left+frame*2*ratio,y:rect.top+rect.height/2};},120);
    await page.mouse.click(rulerPoint.x,rulerPoint.y);
    await page.waitForFunction(()=>document.querySelector('#desk .playhead')?.getAttribute('aria-valuenow')==='120');
    await pane.locator(".time-scroll").evaluate(element=>element.scrollLeft=160);
    await pane.locator(".zv-long").evaluate(element=>{element.style.transform='scale(.8)';element.style.transformOrigin='top left';});
    let line=pane.getByRole("slider",{name:"黄色播放头"}),box=await line.boundingBox();assert(box);
    const hit=await line.evaluate(element=>({width:parseFloat(getComputedStyle(element).width),pointerEvents:getComputedStyle(element).pointerEvents,dx:40*2*element.parentElement.querySelector('.ruler').getBoundingClientRect().width/element.parentElement.querySelector('.ruler').offsetWidth}));
    assert(hit.width>=15&&hit.pointerEvents==='auto');
    await line.evaluate(element=>element.addEventListener('pointerdown',event=>{window.playheadPointer=event.pointerId;window.playheadDragNode=element;},{once:true}));
    await page.mouse.move(box.x+box.width/2,box.y+16);await page.mouse.down();
    assert.equal(await page.evaluate(async()=>{await desk.zvLong.refresh();return document.querySelector('#desk .playhead')===window.playheadDragNode;}),true);
    await page.mouse.move(box.x+box.width/2+hit.dx,box.y+16,{steps:8});await page.mouse.up();
    await page.waitForFunction(()=>document.querySelector('#desk .playhead')?.getAttribute('aria-valuenow')==='160');
    assert.equal(await pane.locator(".card.segment.selected").count(),1);
    await pane.getByRole("button",{name:"黄线处分割",exact:true}).click();await page.waitForFunction(()=>desk.zvLong.getPlan()?.segments.length===3);
    await pane.getByRole("button",{name:"撤销",exact:true}).click();await page.waitForFunction(()=>desk.zvLong.getPlan()?.segments.length===2);
    await pane.locator(".zv-long").evaluate(element=>{element.style.transform='';element.style.transformOrigin='';});await pane.locator(".time-scroll").evaluate(element=>element.scrollLeft=0);
    line=pane.getByRole("slider",{name:"黄色播放头"});box=await line.boundingBox();assert(box);
    await line.evaluate(element=>element.addEventListener('pointerdown',event=>window.playheadPointer=event.pointerId,{once:true}));
    await page.mouse.move(box.x+box.width/2,box.y+16);await page.mouse.down();await page.mouse.move(box.x+box.width/2+30,box.y+16,{steps:3});
    await page.evaluate(()=>document.querySelector('#desk .playhead').dispatchEvent(new PointerEvent('pointercancel',{pointerId:window.playheadPointer,bubbles:true})));
    await page.mouse.up();assert.equal(await line.getAttribute('aria-valuenow'),'160');
    assert.deepEqual(await page.evaluate(async()=>{
        const {readDesk}=await import('/web/long_video_core.mjs');
        const project=JSON.parse(sourceNode.widgets[0].value),nodes=new Map(),links=new Map();
        const graph={links,getNodeById:id=>nodes.get(id)};
        const resolution={id:10,type:'ResolutionSelector',widgets:[{name:'aspect_ratio',value:'9:16 (Portrait Widescreen)'},{name:'megapixels',value:1},{name:'multiple',value:32}],inputs:[],graph};
        const widthRoute={id:11,type:'Reroute',widgets:[],inputs:[{name:'',link:101}],graph};
        const heightRoute={id:12,type:'Reroute',widgets:[],inputs:[{name:'',link:102}],graph};
        const source={id:13,widgets:[{name:'project_data',value:JSON.stringify(project)}],inputs:[{name:'width',link:103},{name:'height',link:104}],graph};
        const target={id:14,inputs:[{name:'media_project',link:105}],graph};
        for(const row of [resolution,widthRoute,heightRoute,source,target])nodes.set(row.id,row);
        links.set(101,{origin_id:10,origin_slot:0});links.set(102,{origin_id:10,origin_slot:1});
        links.set(103,{origin_id:11,origin_slot:0});links.set(104,{origin_id:12,origin_slot:0});links.set(105,{origin_id:13,origin_slot:0});
        const canvas=readDesk(target).project.output_canvas;return [canvas.width,canvas.height];
    }),[768,1376]);
    const ids=await page.evaluate(()=>desk.zvLong.getPlan().segments.map(s=>s.segment_id));
    await pane.getByLabel("每段帧数",{exact:true}).fill("320");await pane.getByLabel("每段帧数",{exact:true}).press("Tab");
    await page.waitForFunction(()=>desk.zvLong.getPlan()?.segments.length===3);
    await pane.getByRole("button",{name:"撤销",exact:true}).click();await page.waitForFunction(()=>desk.zvLong.getPlan()?.segments.length===2);
    assert.deepEqual(await page.evaluate(()=>desk.zvLong.getPlan().segments.map(s=>s.segment_id)),ids);
    await pane.locator(".card.segment").first().click();
    await pane.getByLabel("结束帧（不含）",{exact:true}).fill("300");await pane.getByLabel("结束帧（不含）",{exact:true}).press("Tab");
    await page.waitForFunction(()=>desk.zvLong.getPlan()?.validation.errors.some(x=>x.code==="segment_gap"));
    await pane.getByRole("button",{name:"撤销",exact:true}).click();await page.waitForFunction(()=>desk.zvLong.getPlan()?.validation.ready);
    const form=page.locator("#interview");
    await form.getByLabel("必须保留",{exact:true}).fill("保持躺姿");
    await form.getByRole("button",{name:"检测并对齐全部分段",exact:true}).click();await page.waitForFunction(()=>interview.zvLong.result?.ready);
    await form.getByRole("button",{name:/第 2 段/}).click();
    await form.locator(".asset").filter({hasText:"person.png"}).getByLabel("本段参与").uncheck();
    await form.getByRole("button",{name:"检测并对齐全部分段",exact:true}).click();await page.waitForFunction(()=>interview.zvLong.result?.ready);
    assert.deepEqual(await page.evaluate(()=>interview.zvLong.result.segments[1].reference_plan.routes.ref_images),[]);
    assert.deepEqual(await page.evaluate(()=>interview.zvLong.result.segments[0].reference_plan.routes.ref_images),["p1"]);
    const before=await page.evaluate(()=>sourceNode.widgets[0].value);
    await pane.locator(".card.picture").click();await pane.locator(".lane").nth(1).getByRole("button",{name:"删除",exact:true}).click();
    await page.waitForFunction(()=>desk.zvLong.getPlan()?.media_project.picture_track.length===0);
    assert.equal(await page.evaluate(()=>sourceNode.widgets[0].value),before);
    await pane.getByRole("button",{name:"撤销",exact:true}).click();await page.waitForFunction(()=>desk.zvLong.getPlan()?.media_project.picture_track.length===1);
    await page.evaluate(()=>{const saved=desk.widgets[0].value;desk.zvLong.restore();window.saved=saved;});
    await page.waitForFunction(()=>desk.zvLong.getPlan()?.validation.ready);
    assert.deepEqual(await page.evaluate(()=>desk.zvLong.getPlan().segments.map(s=>s.segment_id)),ids);

    await pane.locator("select").nth(1).selectOption("exact");
    await page.waitForFunction(()=>desk.zvLong.getPlan()?.overlap_alignment==="exact");
    await pane.locator(".card.segment").first().click();
    await assert.doesNotReject(async()=>assert.match(await pane.locator(".bar").filter({hasText:"布局未预填模型长度"}).last().textContent(),/采访执行时按 H3 调用网格补齐/));

    await form.getByRole("button",{name:/第 2 段/}).click();
    await form.getByLabel("必须保留",{exact:true}).fill("只属于将删除的第二段");
    await page.evaluate(()=>window.oldInterviewTextarea=[...document.querySelectorAll('#interview textarea')].find(x=>x.parentElement?.textContent?.startsWith('必须保留')));
    await pane.locator(".card.segment").nth(1).click();
    await pane.locator(".lane").first().getByRole("button",{name:"删除",exact:true}).click();
    await page.waitForFunction(()=>desk.zvLong.getPlan()?.segments.length===1&&interview.zvLong.result?.segments.length===1);
    assert.match(await form.locator(".segments button.active").textContent(),/第 1 段/);
    await page.evaluate(()=>{oldInterviewTextarea.value="过期回调不应写入";oldInterviewTextarea.oninput?.();});
    assert.equal(await page.evaluate(()=>{
        const s=interview.zvLong.getState();return JSON.stringify(s).includes("过期回调不应写入");
    }),false);

    const mode=()=>pane.locator("select").nth(0);
    await mode().selectOption("generation_count");
    await page.waitForFunction(()=>desk.zvLong.getPlan()?.mode==="generation_count");
    await pane.getByLabel("每段帧数",{exact:true}).fill("124");await pane.getByLabel("每段帧数",{exact:true}).press("Tab");
    await page.waitForFunction(()=>desk.zvLong.getSettings().segment_frames===124&&desk.zvLong.getPlan()?.segments[0]?.frame_count===124);
    await pane.getByLabel("重叠帧数",{exact:true}).fill("39");await pane.getByLabel("重叠帧数",{exact:true}).press("Tab");
    await page.waitForFunction(()=>desk.zvLong.getSettings().overlap_frames===39&&desk.zvLong.getPlan()?.effective_overlap_frames===39);
    await pane.getByLabel("段数（仅按段数生成）",{exact:true}).fill("2");await pane.getByLabel("段数（仅按段数生成）",{exact:true}).press("Tab");
    await page.waitForFunction(()=>desk.zvLong.getPlan()?.mode==="generation_count"&&desk.zvLong.getPlan()?.target_frame_count===209&&desk.zvLong.getPlan()?.segments.length===2);
    const autoSegments=await page.evaluate(()=>desk.zvLong.getPlan().segments.map(({segment_id,start_frame,end_frame})=>({segment_id,start_frame,end_frame})));
    await mode().selectOption("generation_manual");
    await page.waitForFunction(()=>desk.zvLong.getPlan()?.mode==="generation_manual"&&desk.zvLong.getPlan()?.target_frame_count===209);
    assert.deepEqual(await page.evaluate(()=>desk.zvLong.getSettings().segments),autoSegments);
    assert.deepEqual(await page.evaluate(()=>desk.zvLong.getPlan().segments.map(({segment_id,start_frame,end_frame})=>({segment_id,start_frame,end_frame}))),autoSegments);
    assert.deepEqual(errors,[]);
    if(process.argv[5]){await mkdir(process.argv[5],{recursive:true});await page.screenshot({path:process.argv[5]+"/long-video-ui.png",fullPage:true});}
    line=pane.getByRole("slider",{name:"黄色播放头"});box=await line.boundingBox();assert(box);await page.mouse.move(box.x+box.width/2,box.y+16);await page.mouse.down();await page.evaluate(()=>desk.onRemoved());await page.mouse.up();await page.waitForTimeout(30);
    assert.deepEqual(errors,[]);
    console.log("LONG_VIDEO_UI_OK: draggable playhead under scroll/zoom, deferred redraw, cancel/removal cleanup, split selection, H3 frame hint, planning, undo, coverage, reroute dimensions, exact inspector, scope migration, stale callback guard, auto-to-manual plan migration, reload");
}finally{await browser?.close();server.kill();}
