import test from 'node:test';
import assert from 'node:assert/strict';
import * as p from '../web/media_evidence_presets.mjs';
import * as e from '../web/media_evidence_core.mjs';

const window={start_seconds:0,end_seconds:17,fps:24};
test('new project defaults to generic v2 with full snapshot',()=>{const project=e.freshProject();assert.equal(project.schema_version,2);assert.deepEqual(project.processing_preset,p.builtin());assert(p.compatibility(window,project.processing_preset).compatible);});
test('v1 migration preserves time and interprets legacy H3; forged validation is discarded',()=>{
    const old=e.freshProject();old.schema_version=1;delete old.processing_preset;old.processing_window=window;old.validation={errors:[]};old.preset_compatibility={compatible:true};
    const migrated=p.migrateProject(old);assert.deepEqual(migrated.processing_window,window);assert.equal(migrated.processing_preset.preset_id,'builtin.minimax-h3.single');assert(!p.compatibility(window,migrated.processing_preset).compatible);assert.equal(migrated.validation,undefined);assert.equal(migrated.preset_compatibility,undefined);assert.equal(old.schema_version,1);
});
test('switching every preset leaves all processing range fields untouched',()=>{let project=e.freshProject();project.processing_window={...window,start_seconds:.01,end_seconds:17.01};const before=p.copy(project.processing_window);for(const preset of p.builtins){project=p.selectPreset(project,preset);assert.deepEqual(project.processing_window,before);}assert.equal(p.windowName(project.processing_preset),'H3 长任务范围');});
test('17-second H3 mismatch reports seconds and frames instead of changing values',()=>{const c=p.compatibility(window,p.builtin('builtin.minimax-h3.single'));assert(!c.compatible);assert.equal(c.frame_count,408);assert.equal(c.effective_max_frames,360);assert.equal(c.effective_max_seconds,15);assert(c.issues.some(e=>e.message.includes('408 帧')&&e.message.includes('15 秒')));assert.equal(window.end_seconds,17);});
test('long task retains H3 segment rules and is only a planning preview',()=>{const preset=p.builtin('builtin.minimax-h3.segmented'),c=p.compatibility({...window,end_seconds:90},preset);assert.equal(preset.preset_version,2);assert.equal(preset.snapshot.rules.overlap_frames,48);assert.equal(preset.snapshot.rules.overlap_alignment,'h3_guide');assert(c.compatible);assert.equal(c.segment_count,7);assert.equal(c.effective_max_frames,360);assert.equal(c.requested_overlap_frames,48);assert.equal(c.effective_overlap_frames,39);assert.equal(c.segment_stride_frames,321);assert.equal(c.rules_only,true);const summary=p.ruleSummary(preset,window);for(const text of ['请求重叠 48 帧','实际 39 帧','H3 Guide','总任务范围不限','尚未执行分段'])assert(summary.includes(text),text);assert(!p.compatibility({...window,end_seconds:1},preset).compatible);});
test('H3 Guide overlap is aligned down at every boundary before counting segments',()=>{
    for(const [requested,actual] of [[1,1],[4,1],[5,5],[12,5],[22,22],[48,39]]){const preset=p.builtin('builtin.minimax-h3.segmented');preset.snapshot.rules.overlap_frames=requested;assert.deepEqual(p.ruleErrors(preset.snapshot),[]);const c=p.compatibility({...window,end_seconds:28},preset);assert(c.compatible);assert.equal(c.frame_count,672);assert.equal(c.requested_overlap_frames,requested);assert.equal(c.effective_overlap_frames,actual);assert.equal(c.segment_stride_frames,360-actual);assert.equal(c.segment_count,2);assert.equal(preset.snapshot.rules.overlap_frames,requested);}
});
test('exact overlap remains model independent and actual overlap controls segment count',()=>{
    const preset=p.builtin('builtin.minimax-h3.segmented'),range={...window,end_seconds:28};assert.equal(p.compatibility(range,preset).segment_count,2); // Requested 48 would incorrectly produce 3.
    Object.assign(preset.snapshot.rules,{overlap_alignment:'exact',overlap_frames:12});let c=p.compatibility(range,preset);assert.deepEqual(p.ruleErrors(preset.snapshot),[]);assert(c.compatible);assert.equal(c.effective_overlap_frames,12);assert.equal(c.segment_stride_frames,348);
    preset.snapshot.rules.overlap_frames=0;c=p.compatibility(range,preset);assert.deepEqual(p.ruleErrors(preset.snapshot),[]);assert.equal(c.effective_overlap_frames,0);assert.equal(c.segment_stride_frames,360);
});
test('alignment strategy and actual overlap relative to segment minimum are validated',()=>{
    for(const [alignment,requested] of [['exact',48],['h3_guide',56],['h3_guide',0],['unknown',12],[null,12]]){const snapshot=p.builtin('builtin.minimax-h3.segmented').snapshot;Object.assign(snapshot.rules,{overlap_alignment:alignment,overlap_frames:requested});assert(p.ruleErrors(snapshot).length);}
});
test('single-window results contain no requested or actual overlap or stride',()=>{for(const id of ['builtin.generic','builtin.minimax-h3.single']){const c=p.compatibility(window,p.builtin(id));for(const key of ['requested_overlap_frames','effective_overlap_frames','segment_stride_frames'])assert.equal(c[key],null);}});
test('legacy v2 snapshot migration keeps exact overlap and frozen identity',()=>{
    const project=p.selectPreset(e.freshProject(),p.builtin('builtin.minimax-h3.segmented'));project.processing_window={...window,end_seconds:28};project.processing_preset.preset_version=1;project.processing_preset.snapshot.rules.overlap_frames=12;delete project.processing_preset.snapshot.rules.overlap_alignment;const before=p.copy(project);
    assert(p.ruleErrors(project.processing_preset.snapshot).length);const snapshot=p.normalizeSnapshot(project.processing_preset.snapshot);assert.equal(snapshot.rules.overlap_alignment,'exact');const migrated=p.migrateProject(project);assert.deepEqual(project,before);assert.deepEqual(migrated.processing_preset.snapshot,snapshot);assert.equal(migrated.processing_preset.preset_version,1);assert.equal(migrated.processing_preset.preset_id,project.processing_preset.preset_id);const c=p.compatibility(migrated.processing_window,migrated.processing_preset);assert.equal(c.effective_overlap_frames,12);assert.equal(c.segment_stride_frames,348);assert(p.samePreset(project.processing_preset,migrated.processing_preset));assert(p.samePreset(migrated.processing_preset,project.processing_preset));assert(!p.samePreset(migrated.processing_preset,p.builtin('builtin.minimax-h3.segmented')));
});
test('custom single-window caps use stricter frames or seconds',()=>{const preset=p.builtin('builtin.minimax-h3.single');preset.snapshot.rules.max_seconds=10;assert.deepEqual(p.ruleErrors(preset.snapshot),[]);const c=p.compatibility(window,preset);assert.equal(c.effective_max_frames,240);assert.equal(c.effective_max_seconds,10);assert(p.ruleSummary(preset,window).includes('有效上限 10 秒 / 240 帧'));});
test('conflicting, nonfinite, fractional frame and empty-name rules are rejected',()=>{
    for(const changes of [{min_frames:400},{max_seconds:1},{max_frames:NaN},{target_fps:Infinity},{target_fps:null},{overlap_frames:-1},{max_frames:1.5},{max_seconds:-1}]){const s=p.builtin('builtin.minimax-h3.single').snapshot;Object.assign(s.rules,changes);assert(p.ruleErrors(s).length);}
    const s=p.builtin().snapshot;s.name=' ';assert(p.ruleErrors(s).length);
});
test('automatic segment conflicts and unsafe overlaps are rejected',()=>{for(const changes of [{segment_min_seconds:16},{segment_max_seconds:null},{overlap_frames:56},{max_seconds:1}]){const s=p.builtin('builtin.minimax-h3.segmented').snapshot;Object.assign(s.rules,changes);assert(p.ruleErrors(s).length);}});
test('generic and nonaligned window drags preserve subframe values',()=>{for(const edge of ['left','right',undefined]){const result=e.dragWindow({start_seconds:2,end_seconds:4,fps:24},.013,edge,[],100,false,null);assert.equal(edge==='right'?result.end_seconds:result.start_seconds,edge==='right'?4.013:2.013);}assert.equal(e.dragWindow({start_seconds:2,end_seconds:4,fps:24},.013,undefined,[2.02],100,true,null).start_seconds,2.02);});
test('aligned custom preset uses target 30 fps rather than a hardcoded 24',()=>{const w={start_seconds:2,end_seconds:4,fps:24},out=e.dragWindow(w,.02,undefined,[],100,false,30);assert.equal(out.start_seconds,61/30);assert.equal(out.end_seconds-out.start_seconds,2);assert.equal(out.fps,24);});
test('snapshots are independent from builtin definitions and later library versions',()=>{const preset=p.builtin('builtin.minimax-h3.single'),project=p.selectPreset(e.freshProject(),preset);preset.preset_version++;preset.snapshot.name='updated';preset.snapshot.rules.max_frames=999;assert.equal(project.processing_preset.preset_version,1);assert.equal(project.processing_preset.snapshot.rules.max_frames,360);assert.equal(p.builtin('builtin.minimax-h3.single').snapshot.rules.max_frames,360);});
test('all builtins have valid expressive rules and distinct same-model strategies',()=>{for(const preset of p.builtins)assert.deepEqual(p.ruleErrors(preset.snapshot),[]);assert.notEqual(p.builtins[1].preset_id,p.builtins[2].preset_id);assert.equal(p.builtins[1].snapshot.rules.target_fps,p.builtins[2].snapshot.rules.target_fps);});
test('snapshot identity is independent of JSON object key ordering',()=>{const a=p.builtin(),b=p.copy(a);b.snapshot.rules=Object.fromEntries(Object.entries(b.snapshot.rules).reverse());assert(p.samePreset(a,b));b.snapshot.name='renamed';assert(!p.samePreset(a,b));});
test('rounded frame count cannot hide time beyond the effective cap',()=>{const preset=p.builtin('builtin.minimax-h3.single');Object.assign(preset.snapshot.rules,{max_frames:240,align_to_grid:false});const c=p.compatibility({...window,end_seconds:10.01},preset);assert.equal(c.frame_count,240);assert.equal(c.effective_max_seconds,10);assert(!c.compatible);});
